// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs heic-to-jpg`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "webp-to-jpg",
    "icon": "🏞️",
    "name": {
      "en": "WebP to JPG",
      "ja": "WebPをJPGに変換",
      "zh": "WebP 转 JPG",
      "de": "WebP zu JPG",
      "es": "WebP a JPG"
    },
    "desc": {
      "en": "Convert WebP images to JPG or PNG.",
      "ja": "WebP画像をJPGまたはPNGに変換します。",
      "zh": "把 WebP 图片转成 JPG 或 PNG。",
      "de": "WebP-Bilder in JPG oder PNG umwandeln.",
      "es": "Convierte imágenes WebP a JPG o PNG."
    }
  },
  {
    "slug": "rename-images",
    "icon": "🏷️",
    "name": {
      "en": "Rename Images in Sequence",
      "ja": "画像を連番でリネーム",
      "zh": "图片按序重命名",
      "de": "Bilder durchnummerieren",
      "es": "Renombrar imágenes en secuencia"
    },
    "desc": {
      "en": "Reorder photos, then download them renamed in sequence as a .zip.",
      "ja": "画像を並び替えて、連番でリネームした ZIP をダウンロード。",
      "zh": "把图片排序后，按顺序重命名并打包成 ZIP 下载。",
      "de": "Fotos sortieren und durchnummeriert als .zip herunterladen.",
      "es": "Reordena tus fotos y descárgalas renombradas en secuencia como un .zip."
    }
  },
  {
    "slug": "images-to-xlsx",
    "icon": "🗃️",
    "name": {
      "en": "Images to XLSX",
      "ja": "画像→Excel一覧",
      "zh": "图片转 Excel 索引",
      "de": "Bilder zu XLSX-Index",
      "es": "Imágenes a índice XLSX"
    },
    "desc": {
      "en": "Build an Excel image index: thumbnail, file name, size, and info per row.",
      "ja": "画像一覧Excelを作成: サムネイル・ファイル名・サイズ・情報を1行ずつ。",
      "zh": "生成图片索引 Excel：每行显示缩略图、文件名、大小和信息。",
      "de": "Erstellt einen Excel-Bildindex: Miniaturbild, Dateiname, Größe und Info pro Zeile.",
      "es": "Crea un índice de imágenes en Excel: miniatura, nombre, tamaño e información por fila."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'heic-to-jpg';
